---
title: "20240424_SDR005_Stat_visualize"
output: html_document
date: "2024-04-24"
---

```{r setup, include=FALSE}

```

## R Markdown



#Load libraries


```{r}

library(Seurat)
library(dplyr)
library(ggplot2)
library(Matrix)
library(reshape2)
library(data.table)
library(stringr)
library(tidyr)
library(scales)
library(rtracklayer)
library(data.table)
library(readr)
library(pheatmap)
library(RColorBrewer)



file_save_dir <- "/Users/dominik.lindenhofer/ownCloud/Shared_project_folder/Paper_drafts/2022_SDR_Paper/Source_data/Individual_files_all"


```

## Load data



```{r}

#Load in Donnachas data for annotation

cDNA_data_Seurat <- readRDS("SDR005_Combined_Geno_full_clustered.rds")

Assays(cDNA_data_Seurat )

metadata <- cDNA_data_Seurat@meta.data
Geno_meta <- cDNA_data_Seurat@assays$Geno_filtered@meta.data
GT_mat <- cDNA_data_Seurat@assays$Geno_filtered$counts %>% as.data.frame

plot_save_dir <- "/Users/dominik.lindenhofer/Documents/Data_Local/Shared_Donnacha_SDR005!/SDR005_data_share/20240205_SDR005_SDRranger_gDNA-V4_cDNA-V5/SDR005_Stat_testing"




```

#___________________________________________________________________________________________________________________________________________________________________________


#___________________________________________________________________________________________________________________________________________________________________________


#___________________________________________________________________________________________________________________________________________________________________________
##check DZ vs LZ - Testing - USE

#Make volcano plot 

#Make volcano plot 


```{r}


group_colors_samples <- c("FL1" = "#FC6736", FL2 = "#FFB0B0", GCB1 = "#0C2D57")
group_colors_CellTypes <- c("Naïve" = "#00CED1", "LZ" = "#D24545", "DZ" = "#51829B" ,"Mem IgM" = "#F6995C", 
                  "Mem IgG" = "#EFBC9B", "Plasma" = "#948979", "Other" = "#D6DAC8", "B unassigned" = "#9CAFAA")


plot_save_dir <- "/Users/dominik.lindenhofer/Documents/Data_Local/Shared_Donnacha_SDR005!/SDR005_data_share/20240205_SDR005_SDRranger_gDNA-V4_cDNA-V5/SDR005_Stat_testing/05_Volcano_plots"


Chi_FL7_one <- read.csv("SDR005_Stat_testing/Chi_FL7_Cell_Types_all.csv") %>% select(-X) %>% mutate(sample = "FL7")
Chi_FL11_one <- read.csv("SDR005_Stat_testing/Chi_FL11_Cell_Types_all.csv") %>% select(-X) %>% mutate(sample = "FL11")
Chi_GCB4_one <- read.csv("SDR005_Stat_testing/Chi_GCB4_Cell_Types_all.csv")  %>% select(-X) %>% mutate(sample = "GCB4")


Chi_comb_one <- rbind(Chi_FL7_one, Chi_FL11_one, Chi_GCB4_one)


#Remove WT - WT 1 ones - filter for DZ and LZ 

Chi_comb_one <- Chi_comb_one %>% 
  filter(State1 == "DZ" & State2 == "LZ") %>%
  filter(!(State1_0_perc == 1 & State2_0_perc == 1)) %>%
  mutate(across(everything(), ~ifelse(is.na(.), 0, .)))

#set_cut_off for number of to filter out low variants 


#Add info
Chi_comb_one <- Chi_comb_one  %>% 
  mutate(State1_edit_count = State1_1_count + State1_2_count,
         State2_edit_count = State2_1_count + State2_2_count,
         State1_edit_perc = State1_1_perc + State1_2_perc,
         State2_edit_perc = State2_1_perc + State2_2_perc,) %>%
  mutate(edit_count_tot = State1_edit_count + State2_edit_count) %>%
  mutate(Significant = if_else(P_val_adj < 0.05, TRUE, FALSE))

#Apply cutoff for variants

#cut_off = 30
#Chi_comb_one <- Chi_comb_one  %>% filter(edit_count_tot > cut_off)

cut_off = 0.05
Chi_comb_one <- Chi_comb_one  %>% filter(State1_edit_perc > cut_off |
                                         State2_edit_perc > cut_off )


#Add delta Chi

Chi_comb_one <- Chi_comb_one %>% mutate(delta_0_perc = State1_0_perc - State2_0_perc,
                                        delta_1_perc = State1_1_perc - State2_1_perc,
                                        delta_2_perc = State1_2_perc - State2_2_perc)



#Add Gene ID

Geno_meta <- cDNA_data_Seurat@assays$Geno_filtered@meta.data
to_add <- Geno_meta %>% select(ID_Geno, Gene_annot, Consequence)
Chi_comb_one <- Chi_comb_one %>% left_join(to_add, by = c("Variant" = "ID_Geno" ))

#Add to highlight

Chi_comb_one  <- Chi_comb_one %>% mutate(target_to_plot_0 = case_when(Significant == TRUE & delta_0_perc > 0 ~ State1,
                                                                      Significant == TRUE & delta_0_perc < 0 ~ State2))


Chi_comb_one  <- Chi_comb_one %>% mutate(target_to_plot_1 = case_when(Significant == TRUE & delta_1_perc > 0 ~ State1,
                                                                      Significant == TRUE & delta_1_perc < 0 ~ State2))


Chi_comb_one  <- Chi_comb_one %>% mutate(target_to_plot_2 = case_when(Significant == TRUE & delta_2_perc > 0 ~ State1,
                                                                      Significant == TRUE & delta_2_perc < 0 ~ State2))


to_order <- c("FL7", "FL11", "GCB4")

Chi_comb_one$sample <- factor(Chi_comb_one$sample, levels = to_order)


#Exclude IG variants

Chi_comb_one_wo_IG <- Chi_comb_one %>% mutate(Gene_annot = if_else(str_detect(Gene_annot, "^IG"), NA_character_, Gene_annot)) %>%   filter(!is.na(Gene_annot))


#Select significant
#All
Chi_comb_one_sel <- Chi_comb_one %>% filter(Significant == TRUE)

#no IG included
Chi_comb_one_wo_IG_sel <- Chi_comb_one_wo_IG %>% filter(Significant == TRUE)


#Make plots
#______________________________________________________________________________________________



#Make volano plot

#group_colors = c("TRUE" = "#990000", "FALSE" = "gray90")



title = "Volcano_plot_Chi_testing_LZ_DZ_delta_0_perc.pdf"

p <- Chi_comb_one %>%
  filter(delta_0_perc != 0) %>%
  ggplot(aes(x = delta_0_perc, y = -log10(P_val_adj), color = target_to_plot_0)) +
  #scale_color_manual(values = group_colors)+
  facet_wrap(~sample, ncol = 3) +
  geom_point(size = 7) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = group_colors_CellTypes) +
  scale_x_continuous(limits = c(-0.3, 0.3)) +
  scale_y_continuous(limits = c(0, 55))+
  labs(title = title , y = "-log10(adj. p-value)") +
  theme_classic()+
      guides(fill = "none", color = "none")

p

ggsave(filename = title, path = plot_save_dir , plot = p, device = "pdf", scale = 1,
       width = 45, height = 15, units = "cm", dpi = 300)


title = "Volcano_plot_Chi_testing_LZ_DZ_delta_1_perc.pdf"

p <- Chi_comb_one %>%
  filter(delta_1_perc != 0) %>%
  ggplot(aes(x = delta_1_perc, y = -log10(P_val_adj), color = target_to_plot_1)) +
  #scale_color_manual(values = group_colors)+
  facet_wrap(~sample, ncol = 3) +
  geom_point(size = 7) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = group_colors_CellTypes) +
  scale_x_continuous(limits = c(-0.3, 0.3)) +
  scale_y_continuous(limits = c(0, 55))+
  labs(title = title , y = "-log10(adj. p-value)") +
  theme_classic()+
      guides(fill = "none", color = "none")

p

ggsave(filename = title, path = plot_save_dir , plot = p, device = "pdf", scale = 1,
       width = 45, height = 15, units = "cm", dpi = 300)



title = "Volcano_plot_Chi_testing_LZ_DZ_delta_2_perc.pdf"

p <- Chi_comb_one %>%
  filter(delta_2_perc != 0) %>%
  ggplot(aes(x = delta_2_perc, y = -log10(P_val_adj), color = target_to_plot_2)) +
  #scale_color_manual(values = group_colors)+
  facet_wrap(~sample, ncol = 3) +
  geom_point(size = 7) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = group_colors_CellTypes) +
  scale_x_continuous(limits = c(-0.3, 0.3)) +
    scale_y_continuous(limits = c(0, 55))+
  labs(title = title , y = "-log10(adj. p-value)") +
  theme_classic()+
      guides(fill = "none", color = "none")

p

ggsave(filename = title, path = plot_save_dir , plot = p, device = "pdf", scale = 1,
       width = 45, height = 15, units = "cm", dpi = 300)





title = "Volcano_plot_Chi_testing_LZ_DZ_delta_1_perc_wo_IG.pdf"

p <- Chi_comb_one_wo_IG %>%
  filter(delta_1_perc != 0) %>%
  ggplot(aes(x = delta_1_perc, y = -log10(P_val_adj), color = target_to_plot_1)) +
  #scale_color_manual(values = group_colors)+
  facet_wrap(~sample, ncol = 3) +
  geom_point(size = 7) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = group_colors_CellTypes) +
  scale_x_continuous(limits = c(-0.3, 0.3)) +
  labs(title = title , y = "-log10(adj. p-value)") +
  theme_classic()+
      guides(fill = "none", color = "none")

p

ggsave(filename = title, path = plot_save_dir , plot = p, device = "pdf", scale = 1,
       width = 45, height = 15, units = "cm", dpi = 300)



title = "Volcano_plot_Chi_testing_LZ_DZ_delta_2_perc_wo_IG.pdf"

p <- Chi_comb_one_wo_IG %>%
  filter(delta_2_perc != 0) %>%
  ggplot(aes(x = delta_2_perc, y = -log10(P_val_adj), color = target_to_plot_2)) +
  #scale_color_manual(values = group_colors)+
  facet_wrap(~sample, ncol = 3) +
  geom_point(size = 7) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = group_colors_CellTypes) +
  scale_x_continuous(limits = c(-0.3, 0.3)) +
  labs(title = title , y = "-log10(adj. p-value)") +
  theme_classic()+
      guides(fill = "none", color = "none")

p

ggsave(filename = title, path = plot_save_dir , plot = p, device = "pdf", scale = 1,
       width = 45, height = 15, units = "cm", dpi = 300)








```





#Make dotplot - enrichment 

```{r}

title = "Dot_plot_Chi_testing_LZ_DZ_delta_1_2_perc.pdf"

p <- Chi_comb_one_sel  %>%
  filter(delta_1_perc != 0) %>%
  filter(delta_2_perc != 0) %>%
  ggplot(aes(x = delta_1_perc, y = delta_2_perc, color = target_to_plot_2)) +
  #scale_color_manual(values = group_colors)+
  facet_wrap(~sample, ncol = 3) +
  geom_point(size = 7) +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = group_colors_CellTypes) +
  scale_x_continuous(limits = c(-0.3, 0.3)) +
  labs(title = title ) +
  theme_classic()+
      guides(fill = "none", color = "none")

p

ggsave(filename = title, path = plot_save_dir , plot = p, device = "pdf", scale = 1,
       width = 45, height = 15, units = "cm", dpi = 300)





title = "Dot_plot_Chi_testing_LZ_DZ_delta_1_2_perc_wo_IG.pdf"
p <- Chi_comb_one_wo_IG_sel  %>%
  filter(delta_1_perc != 0) %>%
  filter(delta_2_perc != 0) %>%
  ggplot(aes(x = delta_1_perc, y = delta_2_perc, color = target_to_plot_2)) +
  #scale_color_manual(values = group_colors)+
  facet_wrap(~sample, ncol = 3) +
  geom_point(size = 7) +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = group_colors_CellTypes) +
  scale_x_continuous(limits = c(-0.3, 0.3)) +
  labs(title = title ) +
  theme_classic()+
      guides(fill = "none", color = "none")

p

ggsave(filename = title, path = plot_save_dir , plot = p, device = "pdf", scale = 1,
       width = 45, height = 15, units = "cm", dpi = 300)

```


#Barplot - erniched genes - USED!


```{r}


#Select only significant ones
#Include IG variants

#Select only significant ones

#Chi_comb_one_wo_IG_sel <- Chi_comb_one_wo_IG %>% filter(Significant == TRUE)

to_plot <- Chi_comb_one_sel %>% 
  group_by(sample, Gene_annot) %>% 
  summarise(count = n(), .groups = 'drop')

# Filter and arrange the data
group_colors_Gene_annot <- to_plot %>% 
  filter(count > 3) %>% 
  arrange(desc(count))

# Get the number of unique Gene_annot values
num_colors <- length(unique(group_colors_Gene_annot$Gene_annot))

# Generate a color palette with the required number of colors
color_palette <- colorRampPalette(c("purple4", "lightblue", "darkblue"))(num_colors)

# Create a named vector for color mapping
color_mapping <- setNames(color_palette, unique(group_colors_Gene_annot$Gene_annot))

# Arrange the Gene_annot factor levels based on the order in group_colors_Gene_annot
to_plot$Gene_annot <- factor(to_plot$Gene_annot, levels = unique(group_colors_Gene_annot$Gene_annot))

# Set the title for the plot
title <- "BarPlot_plot_Chi_testing_LZ_DZ_nCount_sig_variants_per_CellTypes.pdf"

# Create the bar plot
p <- to_plot %>%
  ggplot(aes(x = sample, y = count, fill = Gene_annot)) + 
  geom_bar(stat = "identity", position = "stack") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        plot.title = element_text(hjust = 0.5, face = "bold")) +
  ggtitle(title) +
  labs(x = "Type", y = "Proportion of Cells") +
  scale_fill_manual(values = color_mapping) +
  scale_y_continuous(limits = c(0, 100))

p

# Save the bar plot
ggsave(filename = title, path = plot_save_dir, plot = p, device = "pdf", scale = 1,
       width = 10, height = 15, units = "cm", dpi = 300)




title = "BarPlot_plot_Chi_testing_LZ_DZ_nCount_sig_variants_per_CellTypes_wo_legend.pdf"


p <- to_plot %>%
  ggplot(aes(x = sample, y = count, fill = Gene_annot)) + 
  geom_bar(stat = "identity", position = "stack") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        plot.title = element_text(hjust = 0.5, face = "bold")) +
  ggtitle(title) +
  guides(fill = "none") +
  labs(x = "Type", y = "Proportion of Cells") +
  scale_fill_manual(values = color_mapping) +
  scale_y_continuous(limits = c(0, 100))


ggsave(filename = title, path = plot_save_dir, plot = p, device = "pdf", scale = 1,
       width = 10, height = 15, units = "cm", dpi = 300)
p



to_file <- to_plot %>% mutate(Gene_annot = if_else(is.na(Gene_annot), "Other", Gene_annot))
to_file <- to_file %>% mutate(sample = case_when(sample == "FL7" ~ "FL1",
                                                 sample == "FL11" ~ "FL2",
                                                 sample == "GCB4" ~ "GCB1"))



file_name = "Fig4_M_f_BarPlot_plot_Chi_testing_LZ_DZ_nCount_sig_variants_per_CellTypes.csv"
write.csv(to_file, paste0(file_save_dir, "/", file_name), row.names = FALSE) 




```



#Heatmap - delta variants DZ - LZ 


```{r, fig.width = 6, fig.height = 10}


#plot_save_dir <- "/Users/dominik.lindenhofer/ownCloud/Shared/Shared_Donnacha/SDR005_data_share/20240205_SDR005_SDRranger_gDNA-V4_cDNA-V5/SDR005_Stat_testing/04_LZ_score_plots"

#Select from dataframe what to plot
group_colors_samples <- c(FL7 = "#FC6736", FL11 = "#FFB0B0", GCB4 = "#0C2D57")

# Heatmap preparation
# Select the required columns
to_plot_heatmap <- Chi_comb_one_sel %>% select(delta_0_perc, delta_1_perc, delta_2_perc)

# Set rownames uniquely
for_rownames <- str_c(Chi_comb_one_sel$sample, Chi_comb_one_sel$Variant, sep = "_")
rownames(to_plot_heatmap) <- for_rownames 

# Make sample annotation
sample_annot <- data.frame(ID = for_rownames, sample = Chi_comb_one_sel$sample, Gene_annot = Chi_comb_one_sel$Gene_annot)

mat_col <- data.frame(sample_annot$sample, sample_annot$Gene_annot)
rownames(mat_col) <- rownames(to_plot_heatmap)
colnames(mat_col) <- c("Sample", "Gene")


#For color 

for_color <- Chi_comb_one_sel %>% 
  group_by(sample, Gene_annot) %>% 
  summarise(count = n(), .groups = 'drop')


# Filter and arrange the data for the heatmap colors
group_colors_Gene_annot <- for_color %>% filter(count > 3) %>% arrange(desc(count))
for_color$Gene_annot <- factor(for_color$Gene_annot, levels = unique(group_colors_Gene_annot$Gene_annot))

# Ensure the same color mapping for the heatmap
to_order <- unique(group_colors_Gene_annot$Gene_annot)
to_order <- c(to_order, "Other")

mat_col$Gene <- factor(mat_col$Gene, levels = to_order)
mat_col <- mat_col %>%
  mutate(across(everything(), ~replace_na(., "Other")))

# Make group colors for heatmap as list
group_colors_heatmap <- list(Sample = group_colors_samples, 
                             Gene = c(color_mapping, "Other" = "grey"))

# Define color palette and breaks for heatmap
myBreaks <- seq(-0.26, 0.26, by = 0.01)
myColor <- colorRampPalette(c("#D24545", "white", "#51829B"))(length(myBreaks) - 1)

# Set the title for the heatmap
title <- "SDR005_Perc_DZ_LZ_Heatmap_delta.pdf"

# Create the heatmap
p<- pheatmap(to_plot_heatmap,
         color = myColor,
         scale = "none",
         cluster_cols = FALSE,
         cluster_rows = TRUE,
         border_color = NA,
         show_colnames = TRUE,
         show_rownames = FALSE,
         drop_levels = TRUE,
         annotation_row = mat_col,
         annotation_colors = group_colors_heatmap,
         breaks = myBreaks,
         main = title
)




ggsave(filename = title, path = plot_save_dir, plot = p, device = "pdf", scale = 1,
       width = 10, height = 15, units = "cm", dpi = 300)
p



to_file <- to_plot_heatmap %>% mutate(ID = rownames( to_plot_heatmap))

to_file <- to_file %>%
  mutate(ID = str_replace_all(ID, c("FL7" = "FL1", "FL11" = "FL2", "GCB4" = "GCB1")))

file_name = "Fig4_M_f_SDR005_Perc_DZ_LZ_Heatmap_delta.csv"
write.csv(to_file, paste0(file_save_dir, "/", file_name), row.names = FALSE) 




```






